### ISSUE TITLE
Incorrect active status for last person joining lobby on play again

### ISSUE THREAD

**Issue by alankbi** [rocketden/main#112]
When two people are on the results page and the play again button is clicked, whoever joins/loads the lobby page last, it seems like their player card list is incorrect and has the other person shown as inactive: 

<img width="1682" alt="Screenshot" src="https://user-images.githubusercontent.com/24768574/110186646-ca8c7300-7dca-11eb-987b-2ecde5081041.png">

This has something to do with all the socket messages being sent out at once conflicting both with each other and with the get room request initiated when loading the lobby page.

**Comment by alankbi** [comment]
This was on the branch for #111 so it may or may not occur all the time

**Comment by zpChris** [comment]
@alankbi I think we may have fixed this issue? Should we resolve it?

**Comment by alankbi** [comment]
Yeah it seems to be one of those "bugs" that has popped up at some point in time, but likely isn't very common or regular (or perhaps only happens when testing using npm start). So I think it's fine if we close this

**Comment by zpChris** [comment]
Ok, sounds good - closed!
