### ISSUE TITLE
Remove errorHandler method from frontend

### ISSUE THREAD

**Issue by zpChris** [rocketden/main#44]
I think the way it's done in `Socket.ts` is correct, but for here I noticed that the REST calls already return `axiosErrorHandler(err)` so I think there's no need to make another call to `errorHandler`.

_Originally posted by @alankbi in https://github.com/rocketden/main/pull/43#discussion_r495132297_

**Comment by zpChris** [comment]
Is this still a relevant issue? @alankbi

**Comment by alankbi** [comment]
Nope! Not really, I think we can close this.
